from pathlib import Path
import os

EBRAINS_UTIL_USER_PATH = os.getenv("EBRAINS_UTIL_USER_PATH", os.path.expanduser("~/.ebrains_util"))

EBRAINS_UTIL_CLIENT_ID = os.getenv("EBRAINS_UTIL_CLIENT_ID")
EBRAINS_UTIL_CLIENT_SECRET = os.getenv("EBRAINS_UTIL_CLIENT_SECRET")
EBRAINS_UTIL_REFRESH_TOKEN = os.getenv("EBRAINS_UTIL_REFRESH_TOKEN")
EBRAINS_UTIL_TOKEN_SCOPE = os.getenv("EBRAINS_UTIL_TOKEN_SCOPE")

token_path = Path(EBRAINS_UTIL_USER_PATH) / "auth_token"
